#!/usr/bin/env php
<?php

require_once __DIR__.'/vendor/autoload.php';

$app = new Silex\Application();

#require __DIR__.'/resources/config/dev.php';
#require __DIR__.'/src/app.php';
foreach (new DirectoryIterator(__DIR__ . '/resources/config') as $fileInfo) { if($fileInfo->isDot()) continue; if($fileInfo->getExtension() != 'php') continue; $require_list[] = $fileInfo->getPathname(); }
sort($require_list, SORT_STRING);
foreach($require_list as $file) require $file;

$console = require __DIR__.'/src/console.php';
$console->run();
